# Generated by Django 4.0.3 on 2022-11-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='types',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
