# Generated by Django 4.0.3 on 2022-11-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='total_balance_quantity',
            new_name='total_quantity',
        ),
    ]
